# Generated by Django 2.1.8 on 2021-07-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daniapi', '0002_auto_20210705_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=models.ManyToManyField(null=True, to='daniapi.Tag'),
        ),
    ]
